services:
  db:
    image: postgres
    container_name: db_app
    env_file:
      - .env
  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - 9999:8000
    depends_on:
      - db
    env_file:
      - .env